#!/usr/bin/env perl

use Mojo::Base -strict;

use lib "../cheatsheet/lib";

use Getopt::Long;
use Term::ANSIColor qw(:constants);

use Advent::Utils::Problem qw(run_part submit_part);

GetOptions(
    "all|a"      => \my $all,
    "day|d=i"    => \my $day,
    "notime|t"   => \my $notime,
    "nosubmit|s" => \my $nosubmit,
    "year|y=i"   => \my $year,
);

my ($mday, $month, $cur_year) = (localtime(time))[3..5];

# Set month and day to sensible values
$month++;
$cur_year += 1900;

if (!defined $day && !defined $all) {
    warn "No day provided. Trying to use current day.\n";

    if ($month != 12) {
        warn "Not in December. Aborting.\n";
        exit;
    }

    if ($mday > 25) {
        warn "Not in Advent. Aborting.\n";
        exit;
    }

    $day = $mday;
}

if (!defined $year) {
    warn "No year provided. Using current year.\n";
    $year = $cur_year;
}

if (defined $all) {
    my $end = 25;
    if (defined $day && $day < 25) {
        $end = $day;
    } elsif ($month eq 12) {
        $end = $mday;
    }

    for (1..$end) {
        say BLUE "Running $year day $_:";
        run_part($_, $year, 1);
        last if $_ == 25;
        run_part($_, $year, 2);
        print "\n";
    }
} else {
    # TODO: automatically work out which part to run in the default case?
    say BLUE "Running $year day $day:";
    for (1..2) {
        my $answer = run_part($year, $day, $_);
        chomp $answer;

        if ($answer eq '') {
            say RED "No answer outputted. Skipping part $_.";
            next;
        }

        my $to_submit = (split "\n", $answer)[-1];

        submit_part($year, $day, $_, $to_submit) unless $nosubmit;
    }
}

